"""add svg_code to features and subjects

Revision ID: 5714656b74cd
Revises: 9e7aa4b64b0c
Create Date: 2026-02-06 14:37:15.813855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5714656b74cd'
down_revision: Union[str, Sequence[str], None] = '9e7aa4b64b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('svg_code', sa.Text(), nullable=True))
    op.add_column('subjects', sa.Column('svg_code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'svg_code')
    op.drop_column('features', 'svg_code')
    # ### end Alembic commands ###
