"""tables_fix

Revision ID: 9e7aa4b64b0c
Revises: f010c6bcde6b
Create Date: 2026-02-05 15:34:41.268438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e7aa4b64b0c'
down_revision: Union[str, Sequence[str], None] = 'f010c6bcde6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Сначала создаем новую таблицу achievements
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_index(op.f('ix_achievements_theme'), 'achievements', ['theme'], unique=False)
    op.create_index(op.f('ix_achievements_title'), 'achievements', ['title'], unique=False)
    
    # 2. ПЕРВОЕ - удаляем foreign key constraint из directions
    op.drop_constraint(op.f('directions_track_id_fkey'), 'directions', type_='foreignkey')
    
    # 3. ВТОРОЕ - удаляем колонку track_id из directions
    op.drop_column('directions', 'track_id')
    
    # 4. ТОЛЬКО ПОТОМ - удаляем таблицу tracks
    op.drop_index(op.f('ix_tracks_id'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_name'), table_name='tracks')
    op.drop_table('tracks')  # УБРАТЬ cascade='cascade' - не нужно
    
    # 5. Обновляем features
    op.add_column('features', sa.Column('title', sa.String(), nullable=False))
    op.drop_index(op.f('ix_features_subtitle'), table_name='features')
    op.create_index(op.f('ix_features_title'), 'features', ['title'], unique=False)
    op.drop_constraint(op.f('features_speciality_id_fkey'), 'features', type_='foreignkey')
    op.drop_column('features', 'subtitle')
    op.drop_column('features', 'speciality_id')
    
    # 6. Удаляем image_url из specialities
    op.drop_column('specialities', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialities', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('features', sa.Column('speciality_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('features', sa.Column('subtitle', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('features_speciality_id_fkey'), 'features', 'specialities', ['speciality_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_features_title'), table_name='features')
    op.create_index(op.f('ix_features_subtitle'), 'features', ['subtitle'], unique=False)
    op.drop_column('features', 'title')
    op.add_column('directions', sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('directions_track_id_fkey'), 'directions', 'tracks', ['track_id'], ['id'], ondelete='CASCADE')
    op.create_table('tracks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tracks_pkey'))
    )
    op.create_index(op.f('ix_tracks_name'), 'tracks', ['name'], unique=True)
    op.create_index(op.f('ix_tracks_id'), 'tracks', ['id'], unique=False)
    op.drop_index(op.f('ix_achievements_title'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_theme'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
