"""add_index_to_direction_id

Revision ID: a5112efae115
Revises: fc9d144e2075
Create Date: 2026-02-21 18:59:15.895479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5112efae115'
down_revision: Union[str, Sequence[str], None] = 'fc9d144e2075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_disciplines_direction_id'), 'disciplines', ['direction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disciplines_direction_id'), table_name='disciplines')
    # ### end Alembic commands ###
