"""add group to disciplines

Revision ID: dfd32316669c
Revises: 5714656b74cd
Create Date: 2026-02-08 17:50:09.353457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd32316669c'
down_revision: Union[str, Sequence[str], None] = '5714656b74cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplines', sa.Column('group', sa.String(), server_default='Общие', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disciplines', 'group')
    # ### end Alembic commands ###
