"""remove_unique_discipline_name

Revision ID: fc9d144e2075
Revises: dfd32316669c
Create Date: 2026-02-09 02:45:39.431966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9d144e2075'
down_revision: Union[str, Sequence[str], None] = 'dfd32316669c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disciplines_name'), table_name='disciplines')
    op.create_index(op.f('ix_disciplines_name'), 'disciplines', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disciplines_name'), table_name='disciplines')
    op.create_index(op.f('ix_disciplines_name'), 'disciplines', ['name'], unique=True)
    # ### end Alembic commands ###
